#ifndef PROCESSOR_CONFIG_H
#define PROCESSOR_CONFIG_H

#define CHAT_PROCESSOR_DEFAULT_HOST "0.0.0.0"
#define CHAT_PROCESSOR_DEFAULT_PORT 9191
#define CHAT_PROCESSOR_DEFAULT_DEVICE "/dev/device"
#define CHAT_PROCESSOR_DEFAULT_TIMEOUT_MS 2000
#define CHAT_PROCESSOR_SERVICE_NAME "chat-processor"
#define CHAT_REMOTE_HOST_MAX 256
#define CHAT_DEVICE_PATH_MAX 256

#endif
